[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput --settings=config.settings_production"]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --settings=config.settings_production"
